name: Server CI/CD

on:
  push:
    branches:
      - main 

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20.15.0'

      - name: Install dependencies
        run: |
          cd server
          npm install

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up environment variables
        run: |
          # Create .env file with environment variables
          echo "PORT=4000" >> server/.env
          echo "MONGODB_KEY=${{ secrets.DB_KEY }}" >> server/.env

      - name: Deploy to Vercel (or start server)
        run: |
          cd server
          npm install --save-dev nodemon  # Ensure nodemon is installed
          npm run start
